export const COLORS_PALETTE = {
  // ----- MOOD COLORS -----
  HAPPY: "#FFD166",
  EXCITED: "#FF8FAB",
  CALM: "#3DD9C5",
  SAD: "#7C5CFF",
  ANGRY: "#FF7A59",
  SCARED: "#5B8CFF",
  TIRED: "#8E9AAF",
  SURPRISED: "#A06BFF",

  // ----- APP SURFACES -----
  BACKGROUND: "#FFF8F2",
  BACKGROUND_ALT: "#F7F7FF",
  CARD_BG: "#FFFFFF",
  CARD_SOFT: "#FFF2FB",
  CARD_HIGHLIGHT: "#EEF4FF",
  OVERLAY: "#1F244012",

  // ----- TEXT -----
  TEXT_PRIMARY: "#1F2440",
  TEXT_SECONDARY: "#5C6384",
  TEXT_TERTIARY: "#8C92B3",
  TEXT_LIGHT: "#FFFFFF",

  // ----- BRAND ACCENTS -----
  ACCENT_1: "#FFD166",
  ACCENT_2: "#6C63FF",
  ACCENT_3: "#3DD9C5",
  ACCENT_4: "#FF8FAB",

  // ----- BORDERS AND STATES -----
  BORDER_DEFAULT: "#E8E1F3",
  BORDER_FOCUS: "#6C63FF",
  SELECTION_BG: "#6C63FF14",
  SELECTION_BORDER: "#6C63FF",
  SUCCESS_BG: "#E8FFF8",
  WARNING_BG: "#FFF6DA",

  // ----- BUTTONS AND ACTIONS -----
  BUTTON_PRIMARY: "#6C63FF",
  BUTTON_SECONDARY: "#FF8FAB",
  BUTTON_TEXT: "#FFFFFF",
};
