export const COLORS_PALETTE = {
  // ----- MOOD COLORS -----
  HAPPY: "#FFD93D",
  EXCITED: "#FF6B6B",
  CALM: "#4ECDC4",
  SAD: "#6C5CE7",
  ANGRY: "#FF8C42",
  SCARED: "#A8D8EA",
  TIRED: "#95E1D3",
  SURPRISED: "#F38181",

  BACKGROUND: "#FFF5F7",
  CARD_BG: "#FFFFFF",

  // ----- TITLES -----
  TEXT_PRIMARY: "#2D3436",
  TEXT_SECONDARY: "#636E72",
  TEXT_LIGHT: "#FFFFFF",

  // ----- DECORATIVE ELEMENTS -----
  ACCENT_1: "#FFD93D",
  ACCENT_2: "#4ECDC4",
  ACCENT_3: "#95E1D3",

  // ----- BORDERS AND STATES -----
  BORDER_DEFAULT: "#4ECDC4",
  BORDER_FOCUS: "#6C5CE7",
  SELECTION_BG: "#4ECDC415",
  SELECTION_BORDER: "#4ECDC4",

  // ----- BUTTONS AND ACTIONS -----
  BUTTON_PRIMARY: "#4ECDC4",
  BUTTON_SECONDARY: "#6C5CE7",
  BUTTON_TEXT: "#FFFFFF",
};
